### ISSUE TITLE
Slow loading time when combining business types with including themes functions.

### ISSUE THREAD

**Issue by Dennisprins93** [nexusthemes/nxs-portfolio#1]
Currently i'm working on a custom PHP implementation of the portfolio plugin, and everything is working very well, except for one thing.

What I'm doing is: I'm building a loop through all the business types, to show all the themes in the separate business types, to show all themes in once. But i'm somehow experiencing huge loading-times when it comes to looping through the second function on line 37 as in the screenshot below.
I've posted a screenshot of the code below this post, and as soon as I add the "nxs_portfolio_nxsthemesinbusinesstype($type)" code on line 37, my browser collapses, and says that the page cannot be openend anymore. If I remove the code, the code works fine, but is only showing me the names of the business types.

To be clear: when i'm running the separate functions nxs_portfolio_nxsthemesinbusinesstype and nxs_portfolio_nxsbusinesstypesshortcode, both functions are giving nice results, but as soon as I combine the "themes functions" with the "business types functions", the whole thing collapses. I think it's due to high loading time on nexus server? Can this somehow be solved?

![screen shot 2016-06-05 at 20 30 27](https://cloud.githubusercontent.com/assets/9679179/15807378/28c57c52-2b5d-11e6-9e2e-67bc308d151f.png)

**Comment by barkgj** [comment]
See discussion in the FB group.
